// react-surfaces/components/typo/Header.tsx
import React from 'react'

import styles from '../../../common/typo.module.sass'

type HeaderProps = {
  children?: React.ReactNode
}

export const Header: React.FC<HeaderProps> = ({ children }) => (
  <h1 className={styles.header}>{children}</h1>
)

export const Subheader: React.FC<HeaderProps> = ({ children }) => (
  <h2 className={styles.subheader}>{children}</h2>
)

export const ContrastHeader: React.FC<HeaderProps> = ({ children }) => (
  <h3 className={styles['contrast-header']}>{children}</h3>
)

export const GutterHeader: React.FC<HeaderProps> = ({ children }) => (
  <h4 className={styles['gutter-header']}>{children}</h4>
)

// solid-surfaces/components/typo/Header.tsx
import { ParentComponent } from 'solid-js'

import styles from '../../../common/typo.module.sass'

export const Header: ParentComponent = ({ children }) => (
  <h1 class={styles.header}>{children}</h1>
)

export const Subheader: ParentComponent = ({ children }) => (
  <h2 class={styles.subheader}>{children}</h2>
)

export const ContrastHeader: ParentComponent = ({ children }) => (
  <h3 class={styles['contrast-header']}>{children}</h3>
)

export const GutterHeader: ParentComponent = ({ children }) => (
  <h4 class={styles['gutter-header']}>{children}</h4>
)
