// react-surfaces/components/Button.tsx
import React from 'react'
import styles from '../../common/button.module.sass'

type ButtonProps = React.PropsWithChildren<{
  primary?: boolean
}> &
  React.ButtonHTMLAttributes<HTMLButtonElement>

export default ({ primary, children, ...props }: ButtonProps) => (
  <button className={`${styles.container} ${primary ? styles.primary : ''}`} {...props}>
    {children}
  </button>
)

// solid-surfaces/components/Button.tsx
import { JSX, ParentComponent, Ref } from 'solid-js'

import styles from '../../common/button.module.sass'

type ButtonProps = {
  primary?: boolean
  ref?: Ref<HTMLButtonElement>
} & JSX.HTMLAttributes<HTMLButtonElement>

const Button: ParentComponent<ButtonProps> = ({ primary, children, ref, ...props }) => (
  <button
    ref={ref}
    classList={{ [styles.container]: true, [styles.primary]: primary }}
    {...props}
  >
    {children}
  </button>
)

export default Button
