// react-surfaces/components/Grid.tsx
import styles from '../../common/grid.module.sass'

type GridProps = {
  children: React.ReactNode | undefined
}

const Grid = ({ children }: GridProps) => (
  <div className={styles.container}>
    <div className={styles.background_grid}>
      <div className={styles.background_grid_filler_column} />
      <div className={styles.background_grid_filler_column} />
      <div className={styles.background_grid_filler_column} />
      <div className={styles.background_grid_filler_column} />
      <div className={styles.background_grid_filler_column} />
      <div className={styles.background_grid_filler_column} />
      <div className={styles.background_grid_filler_column} />
      <div className={styles.background_grid_filler_column} />
    </div>
    <div className={styles.grid}>{children}</div>
  </div>
)

export default Grid

// solid-surfaces/components/Grid.tsx
import { ParentComponent } from 'solid-js'

import styles from '../../common/grid.module.sass'

const Grid: ParentComponent = ({ children }) => (
  <div class={styles.container}>
    <div class={styles.background_grid}>
      <div class={styles.background_grid_filler_column} />
      <div class={styles.background_grid_filler_column} />
      <div class={styles.background_grid_filler_column} />
      <div class={styles.background_grid_filler_column} />
      <div class={styles.background_grid_filler_column} />
      <div class={styles.background_grid_filler_column} />
      <div class={styles.background_grid_filler_column} />
      <div class={styles.background_grid_filler_column} />
    </div>
    <div class={styles.grid}>{children}</div>
  </div>
)

export default Grid
