// solid-surfaces/App.tsx
import './App.scss'
import '../common/button.sass'

import { Component, createSignal } from 'solid-js'

const App: Component = () => {
  const [counter, setCounter] = createSignal(0)
  setInterval(setCounter, 1000, (c: number) => c + 1)

  return (
    <>
      <div>
        <h1 class="header">{counter()}</h1>
      </div>
      <h1>Hello world!</h1>
      <button class="pink-button">Good Morning</button>
    </>
  )
}

export default App

// react-surfaces/App.tsx
import React from 'react'
import { useState } from 'react'

import '../common/button.sass'

const App = () => {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <header className="App-header">
        <h1>Vite + React</h1>
      </header>
      <button className="pink-button" onClick={() => setCount((count) => count + 1)}>
        count is: {count}
      </button>
    </div>
  )
}

export default App
